clients/urls.py
from django.urls import path
from .views import *

app_name = 'clients'

urlpatterns = [
    path("", ClientsListView.as_view(), name='clients_list'),
    path("create", ClientCreateView.as_view(), name='client_create'),
    path("<int:pk>", ClientDetailView.as_view(), name='client_detail'),
    path("<int:pk>/update", ClientUpdateView.as_view(), name='client_update'),
    path("<int:pk>/delete", ClientDeleteView.as_view(), name='client_delete'),
    path('<int:pk>/visits/create', visit_create, name='visit_create'),
    path("search", ClientSearchView.as_view(), name='client_search'),
]

orto_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('clients.urls')),
]

clients/models.py
from django.db import models

# Create your models here.


class Clients(models.Model):
    fullname = models.CharField(max_length=100)
    birthdate = models.DateField()
    email = models.CharField(max_length=150, blank=True, null=True)
    phonenumber = models.CharField(max_length=20, blank=True, null=True)
    note = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return self.fullname


class Visits(models.Model):
    visiting_date = models.DateTimeField
    client_id = models.ForeignKey(Clients, on_delete=models.CASCADE, related_name='visit')

clients/forms.py
from django.forms import ModelForm, DateInput
from .models import Clients, Visits


class ClientsForm(ModelForm):
    class Meta:
        model = Clients
        fields = '__all__'
        widgets = {
            'birthdate': DateInput(attrs={'type': 'date'}),
        }


class VisitsForm(ModelForm):
    class Meta:
        model = Visits

clients/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.decorators.http import require_POST


from .models import Clients
from .forms import ClientsForm, VisitsForm


class ClientsListView(ListView):
    model = Clients
    template_name = 'clients/clients_list.html'
    context_object_name = 'clients'


class ClientDetailView(DetailView):
    model = Clients
    template_name = 'clients/client_detail.html'
    context_object_name = 'client'


class ClientCreateView(CreateView):
    form_class = ClientsForm
    template_name = 'clients/client_create.html'
    success_url = reverse_lazy('clients:clients_list')


class ClientUpdateView(UpdateView):
    model = Clients
    form_class = ClientsForm
    template_name = 'clients/client_update.html'
    context_object_name = 'client'

    def get_success_url(self):
        return reverse('clients:client_detail', kwargs={'pk': self.object.id})


class ClientDeleteView(View):
    def get(self, request, pk):
        client_to_delete = get_object_or_404(Clients, pk=pk)
        client_to_delete.delete()
        return HttpResponseRedirect(reverse('clients:clients_list'))


class ClientSearchView(ListView):
    model = Clients
    template_name = 'clients/client_search.html'
    context_object_name = 'clients'

    def get_queryset(self):
        return Clients.objects.filter(fullname__icontains=self.request.GET.get('name'))

    def get_context_data(self, **kwargs):
        context = super(ClientSearchView, self).get_context_data(**kwargs)
        context['find_name'] = self.request.GET.get('name')
        return context


@require_POST
def visit_create(request, client_id):
    client = get_object_or_404(Clients,
                               id=client_id)

    visit = None
    form = ClientsForm(data=request.POST)
    if form.is_valid():
        visit = form.save(commit=False)
        visit.client = client
        visit.save()
    return render(request,
                  'clients/visit_create.html',
                  {'client': client, 'visit': visit, 'form': form})

clients/templates/clients/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Orto app{% endblock %}</title>
</head>
<body>
    <h1><a href="{% url 'clients:clients_list' %}">Главная</a></h1>
    {% block content%}
        There must be some content
    {% endblock %}
</body>
</html>

clients/templates/clients/client_create.html
{% extends "clients/base.html" %}
{% block content %}
<form action="{% url 'clients:client_create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="save">
</form>
{% endblock %}

clients/templates/clients/client_detail.html
{% extends "clients/base.html" %}
{% block content %}
<p>{{ client.fullname }}</p>
<p>Дата рождения: {{ client.birthdate }}</p>
<p>Электронная почта: {{ client.email }}</p>
<p>Номер телефона: {{ client.phonenumber }}</p>
<p>Заметка: {{ client.note }}</p>
<p><a href="{% url 'clients:client_update' client.id %}">Изменить</a></p>
<p><a href="{% url 'clients:client_delete' client.id %}">Удалить</a></p>
{% endblock %}

clients/templates/clients/client_search.html
{% extends "clients/base.html" %}
{% block content %}
<form action="{% url 'clients:client_search' %}" method="get">
    <input name="name" type="text" placeholder="Поиск" value="{{ find_name }}">
    <button type="submit">Поиск</button>
</form>
{% if clients %}
    {% for client in clients %}
        <p><a href="{% url 'clients:client_detail' client.id %}">{{ client.fullname }}</a></p>
    {% endfor %}
{% else %}
    <p>Ничего нет</p>
{% endif %}
{% endblock %}

clients/templates/clients/client_update.html
{% extends "clients/base.html" %}
{% block content %}
<form action="{% url 'clients:client_update' client.id %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="save">
</form>
{% endblock %}

clients/templates/clients/clients_list.html
{% extends "clients/base.html" %}
{% block content %}
<p><a href="{% url 'clients:client_create' %}">Создать клиента</a></p>

<form action="{% url 'clients:client_search' %}" method="get">
    <input name="name" type="text" placeholder="Поиск">
    <button type="submit">Поиск</button>
</form>{% for client in clients %}

<p><a href="{% url 'clients:client_detail' client.id %}">{{ client.fullname }}</a></p>
{% endfor %}
{% endblock %}

clients/templates/clients/visit_create.html
<h2>Создать посещение</h2>
<form action="{ url 'clients:visit_create' client.id}">
    {{ form.as_p }}
    {% csrf_token 5}
    <input type="submit">
</form>